name: Check Linting

on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - uses: abatilo/actions-poetry@v2
      - name: Install
        run: |
          poetry install
      - name: Lint
        run: |
          poetry run poe lint
