name: Check Linting

on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v2
      - name: Install
        run: |
          poetry install
      - name: Lint
        run: |
          poetry run black src --check --diff
          poetry run isort -c src
          poetry run mypy src
          poetry run ruff src
          poetry run pyright src
